### PR TITLE
Replace __name__ by __tablename__

### PR DESCRIPTION
**Pull request by simnh**
this is linked to https://github.com/openego/ego.io/issues/12

### CODE REVIEW

**Comment by simnh** [comment]
Ok, I just checked in https://github.com/openego/ego.io/blob/master/egoio/db_tables/calc_ego_mv_powerflow.py , there the Storage is indeed named `Storage` and not `StorageUnit``as defined in the corresponding hv - file.  

So maybe my fix was not right, and we should just rename the class inside  https://github.com/openego/ego.io/blob/master/egoio/db_tables/calc_ego_hv_powerflow.py from `StorageUnit` to `Storage`?

**Comment by simnh** [comment]
Can you check, and and fix this, or give a comment on this @mariusves ?

**Comment by mariusves** [comment]
Closed due to already available fix (see f0a494b0ef070d3585326e7410035595d5381c80)

**Comment by nesnoj** [comment]
@mariusves, @simnh : Plz delete branch as well if no longer needed

**But**: I think the issue rather concerns ego.io than ego.powerflow. In your current version of [`StorageUnit`](https://github.com/openego/ego.io/blob/b7749177a3b8d59a81dec3dbf1d7b8a5a7d5d3ae/egoio/db_tables/calc_ego_hv_powerflow.py#L153) you use the table 'storage' and manually changed the class name. @MGlauer's script to automatically generate table defs (see [issue 8 in ego.io](https://github.com/openego/ego.io/issues/8)) in ego.io will probably destroy your modification since it uses the table name as class name.
I don't really see why you can't use 'Storage'?

**Pull request closed without merging**
